In [12]:
palindromo = "anita lava la tina"

In [11]:
print("%s es un palindromo!!!!" % palindromo) if palindromo.replace(" ", "") == palindromo.replace(" ", "")[::-1] else print("'%s' no es un palindromo =(" % palindromo)

'anita lava las tinas' no es un palindromo =(


# Introducción a numpy

#### Librería optimizada para realizar cálculos numéricos con vectores y matrices

In [2]:
import numpy as np #importar librería numpy

#### Podemos definir arrays a partir de listas

In [16]:
arr = np.array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])
print(type(arr)) #definiendo un array a través de una lista y se imprime el tipo

<class 'numpy.ndarray'>


In [17]:
arr.shape #2 filas x 10 columnas

(2, 10)

In [21]:
lista = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19] #lista inicial
arr = np.array(lista) #nueva variable que a la que se le assigna la funcion de transformar en array la lista.
print (type(arr))

<class 'numpy.ndarray'>


In [23]:
[2] + [4] #una forma de crear un arreglo.

[2, 4]

In [25]:
l = [2] #"l" es un arreglo con un valor que es 2
l.append(4) #a "l" le agregamos el valor 4

In [28]:
l #llamamos el arreglo con el nuevo valor.

[2, 4]

#### Los arrays y las listas se comportan diferente frente operaciones matematicas con números

In [22]:
print(lista + 2) # Error. Los arrays deben ser homogeneos es decir solo se pueden concatenar con elementos iguales.
# print(arr + 2) # suma 2 a cada elemento ahora que se ha transformado la lista en array con la función np.array(lista)

TypeError: can only concatenate list (not "int") to list

In [27]:
#print(lista * 2) # duplica la lista
print(arr * 2) # multiplica por dos cada elemento

[20 22 24 26 28 30 32 34 36 38]


#### Los arrays y las listas se comportan diferente frente a operaciones con otros arrays/listas

In [34]:
lista1 = [1, 2, 3, 4, 5]
lista2 = [5, 4, 3, 2, 1]

arr1 = np.array(lista1)
arr2 = np.array(lista2)

In [35]:
print('suma de listas =', lista1 + lista2) # concatena (une) las dos listas
print('suma de arreglos =', arr1 + arr2) # suma los elementos de cada arreglo como columnas

suma de listas = [1, 2, 3, 4, 5, 5, 4, 3, 2, 1]
suma de arreglos = [6 6 6 6 6]


In [31]:
# print(lista1 * lista2) # da error no se pueden multiplicar las listas
print('multiplicación de arreglos =', arr1 * arr2) # multiplica los elementos de cada arreglo

multiplicación de arreglos = [5 8 9 8 5]


In [32]:
print('resta =', arr1 - arr2) #Resta de arrays
print('division =', arr1 / arr2) #División de arrays
print('exponenciacion =', arr1 ** arr2) #potencias de arrays
print('combinacion de operaciones =', (arr1 - arr2)/(arr1 + arr2) * arr1) #mezcla de operaciones

resta = [-4 -2  0  2  4]
division = [0.2 0.5 1.  2.  5. ]
exponenciacion = [ 1 16 27 16  5]
combinacion de operaciones = [-0.66666667 -0.66666667  0.          1.33333333  3.33333333]


#### Para arrays1d la indexación funciona igual que para las listas

In [33]:
lista = [10, 11, 12, 13, 14, 15, 16, 17, 18, 19] #se declara la variable con una lista en su interior
arr = np.array(lista) #se declara la variable arr con la función que transforma la lista en array dentro.

In [34]:
print(lista[0], arr[0]) # devuelve el 1er elemento
print(lista[4], arr[4]) # devuelve el 5to elemento
print(lista[:3], arr[:3]) #devuelve los primeros 3 elementos
print(lista[1:7], arr[1:7])#devuelve los elementos desde la posición 1 al 7 (no inclusive)
print(lista[3:], arr[3:])#devuelve desde el 3er elemento en adelante
print(lista[-1], arr[-1])#devuelve el último elemento
print(lista[:-1], arr[:-1])#devuelve desde el 1er elemento al penúltimo
print(lista[::-1], arr[::-1])#devuelve la lista en reversa

10 10
14 14
[10, 11, 12] [10 11 12]
[11, 12, 13, 14, 15, 16] [11 12 13 14 15 16]
[13, 14, 15, 16, 17, 18, 19] [13 14 15 16 17 18 19]
19 19
[10, 11, 12, 13, 14, 15, 16, 17, 18] [10 11 12 13 14 15 16 17 18]
[19, 18, 17, 16, 15, 14, 13, 12, 11, 10] [19 18 17 16 15 14 13 12 11 10]


In [35]:
lista[2:5] = [22, 23, 24] #reemplaza las posiciones desde el 2do lugar al quinto por los nuevos valores
arr[2:5] = [22, 23, 24]#reemplaza las posiciones desde el 2do lugar al quinto por los nuevos valores
print(lista) #se imprime lista con los cambios.
print(arr)

[10, 11, 22, 23, 24, 15, 16, 17, 18, 19]
[10 11 22 23 24 15 16 17 18 19]


# Arreglos multidimensionales

#### Las listas son cadenas unidimensionales de elementos. Los arreglos pueden ser multidimensionales

In [40]:
lista = [[0, 1, 3], [3, 4, 5]] #lista unidimensional con 2 lístas dentro
array_2d = np.array(lista) #se transforma la lista en array
array_2d #se genera el array de dos dimensiones

array([[0, 1, 3],
       [3, 4, 5]])

In [43]:
print(array_2d.ndim) #se utiliza ndim para indicar cuántas dimensiones tiene el arreglo.

2


In [39]:
print(array_2d.shape) #se utiliza .shape para indicar que forma tiene el arreglo, en este caso son dos filas por 3 columnas.

(2, 3)


In [40]:
print(array_2d.size) #se utiliza .size para indicar el tamaño de la muestra en este caso arroja 6 valores.

6


#### En scikit-learn array_2d=(samples, features)

#### **Desafío:** armar un array 3d a partir de una lista de listas <br>
#### Queremos que *array3d.ndim==3* devuelva *True*

In [46]:
lista = [[0, 1], [2, 3], [4, 6]] #lista de listas
# lista = [lista, lista]
arr3d = np.array([lista, lista, lista]) #se define la variablle arr3d que transforma las listas en array de 3 dimensiones
print(arr3d.shape) #se corrobora la forma de los array, son 3 matrices x 3 filas x 2 columnas
print(arr3d.dtype)
arr3d.ndim==3 #indicar dimensiones si es igual a 3 mostrar True
print (arr3d)

(3, 3, 2)
int64
[[[0 1]
  [2 3]
  [4 6]]

 [[0 1]
  [2 3]
  [4 6]]

 [[0 1]
  [2 3]
  [4 6]]]


In [48]:
np.array([[1, 2], [1, 2, 3]]).dtype

dtype('O')

In [52]:
lista[0:2]

[[0, 1], [2, 3]]

In [53]:
lista[0][1]

1

In [56]:
lista[0][1][0]

2

In [54]:
arr3d

array([[[0, 1],
        [2, 3],
        [4, 6]],

       [[0, 1],
        [2, 3],
        [4, 6]],

       [[0, 1],
        [2, 3],
        [4, 6]]])

In [69]:
# print(arr2d[0, 1])
# print(arr3d[0, 1, 1])
# print(arr3d[0, 1, :])
# print(arr3d[0, 1, :2])
# print(arr3d[0, :, /:1])
print(arr3d[0, 1, -1])

3


In [73]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr, arr.shape)
print(arr.reshape(2, 3), arr.reshape(3, 2).shape)


[1 2 3 4 5 6] (6,)
[[1 2 3]
 [4 5 6]] (3, 2)


# Creación de arreglos

In [6]:
print(np.zeros(10)) #genera un arreglo de zeros
# print(np.zeros((3, 2)))
#print(np.zeros((10, 5)))
print(np.zeros((2, 2, 2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [ ]:
# np.ones(10)#arreglo con 1
# np.ones((3, 2))
# np.ones((10, 5))
# np.ones((2, 2, 2))

In [ ]:
print(np.random.rand(10), '\n')
print(np.random.rand(3, 2), '\n')
print(np.random.rand(10, 5), '\n')
print(np.random.rand(2, 2, 2))

In [ ]:
print(np.random.randn(10), '\n')
print(np.random.randn(3, 2), '\n')
print(np.random.randn(10, 5), '\n')
print(np.random.randn(2, 2, 2))

In [9]:
np.random.randint(5) #saca un aleatoreo, según el número o funcion que le entregue

0

In [ ]:
print(np.random.randint(10, size=10), '\n')
print(np.random.randint(10, size=(3, 3)), '\n')

In [10]:
# np.arange(10)
# np.arange(0, 10, 1) # start, stop, step
np.arange(2, 16, 2)
np.arange(0, 10, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [12]:
np.linspace(0, 10, 70) # start, stop, length
np.linspace(0, 10, 101)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [14]:
np.append(np.zeros(6), 1.)
# np.append(np.zeros(5), np.ones(5))
# np.concatenate((np.zeros(5), np.ones(5), np.arange(5)))
# np.stack((np.zeros(5), np.ones(5)), axis=0)
# np.stack((np.zeros(5), np.ones(5)), axis=1)

array([0., 0., 0., 0., 0., 0., 1.])

In [ ]:
# print(np.nan, np.inf)
# print(np.exp(1000))
np.zeros((10, 10)) * np.nan

**Desafío:** crear un array 1d de longitud 10 que tenga el número 5 en todas sus posiciones <br>
**Desafío:** crear un array 1d que tenga todos los números del 1 al 40 pero con todos los pares primero y los impares después <br>
**Desafío usando google:** crear un array 1d de longitud 20 que tenga los números del 1 al 20 desordenados <br>

In [ ]:
#np.ones(10) * 5
np.append(np.arange(2, 42, 2), np.arange(1, 40, 2))

# Funciones

## Promedio o media
$$
X = (x_1, x_2,...,x_N)
$$

$$
\bar{x}=\frac{1}{N}\sum_{n=1}^{N} x_n
$$

#### Valor esperado

In [ ]:
X = np.ones(7) * 4
print(X)
print(np.mean(X))

In [ ]:
X = np.arange(2, 7)
np.random.shuffle(X)
print(X)
print(np.mean(X))

In [ ]:
X = np.arange(1, 8)
print(X)
print(np.mean(X))

In [ ]:
X = np.arange(1, 10).reshape(3, 3)
print(X, '\n')
print(np.mean(X, 0), '\n') # o np.mean(X, axis=0)
print(np.mean(X, 1)) # o np.mean(X, axis=1)

In [ ]:
np.mean?

## Varianza
$$
\sigma_x=\frac{1}{N}\sum_{n=1}^{N} (x_n - \bar{x})^2
$$

#### Mide la dispersión de los valores alrededor de la media

In [ ]:
X = np.ones(7) * 4
print(X)
print(np.var(X))

In [ ]:
X = np.arange(2, 7)
print(X)
print(np.var(X))

In [ ]:
X = np.arange(1, 8)
print(X)
print(np.var(X))

In [ ]:
X = np.arange(1, 10).reshape(3, 3)
print(X, '\n')
print(np.var(X, 0), '\n') # o np.var(X, axis=0)
print(np.var(X, 1)) # o np.var(X, axis=1)

Otras

In [ ]:
X = np.arange(-3, 4)
print(X)
print(np.min(X))
print(np.max(X))
print(np.sum(X))
# también funcionan con axis

In [ ]:
X = np.arange(-3, 4)
print(np.abs(X))
print(np.sign(X))

In [ ]:
X = np.arange(1, 8)
np.random.shuffle(X)
print(X)
arg_min = np.argmin(X)
arg_max = np.argmax(X)
print(arg_min, X[arg_min])
print(arg_max, X[arg_max])

In [ ]:
X = np.arange(1, 8) + 0.7
print(X)
print(np.round(X, 0))

# Máscaras booleanas
se van a usar mucho

In [ ]:
arr = np.array([0., 1.])
mask = np.array([True, False])
print(mask)
print(mask.dtype)
print(arr)
print(arr.dtype)

In [ ]:
arr = np.arange(10)
print(arr)
print(arr > 3)
print(~(arr > 3))
print((arr > 3) & (arr < 8))
print((arr < 3) | (arr > 8))

#### Puedo filtrar datos
Entender muy bien que es MASK y su diferencia con una operación para filtrar

In [ ]:
arr = np.array([5., 10.])
mask = np.array([True, False])
print(arr[mask])

In [ ]:
arr = np.arange(10)
mask = (arr > 3) & (arr < 8)
print(arr[mask])

#### Devuelvo siempre un array 1d

In [ ]:
arr = np.arange(10).reshape(2, 5)
mask = (arr > 3) & (arr < 8)
print(arr)
print(arr[mask])

#### Puedo usar *np.zeros* y *np.ones* para crear arrays de False y True

In [ ]:
np.zeros(10, dtype=bool)
# np.ones(10, dtype=bool)

#### np.any y np.all

In [ ]:
mask = np.zeros(10, dtype=bool)
print(mask, '  any=', np.any(mask))
mask[5] = True
print(mask, '  any=', np.any(mask))

In [ ]:
mask = np.ones(10, dtype=bool)
print(mask, '  all=', np.all(mask))
mask[5] = False
print(mask, '  all=', np.all(mask))

In [ ]:
mask = np.array(np.random.randint(2, size=(3, 3)), dtype=bool)
print(mask, '\n')
print(np.all(mask, 0), '\n')
print(np.all(mask, 1))

In [15]:
mask = np.array(np.random.randint(2, size=10), dtype=bool)
print(mask, '\n')
print(np.where(mask), '\n')

[False False False False  True False  True  True False  True] 

(array([4, 6, 7, 9]),) 



In [16]:
mask = np.array(np.random.randint(2, size=(3, 3)), dtype=bool)
print(mask, '\n')
print(np.where(mask), '\n') #esto se va usar mucho, te muestra donde están los que cumplen la función.

[[ True  True False]
 [False False  True]
 [ True False  True]] 

(array([0, 0, 1, 2, 2]), array([0, 1, 2, 0, 2])) 



# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn y llenar con ceros todas las posiciones menores a 0 usando una máscara
9. Crear el array np.arange(10) e insertar el número 0 en todos los valores pares usando una máscara
10. Crear un arreglo de números aleatorios de longitud 10. Hallar el valor mínimo y reemplazarlo por 0